version: '3'

services:
  # racing API
  api:
    build: ./api 
    container_name: api
    ports:
      - "${API_PORT}:8080"
    environment:
      - NODE_ENV=development
      - INTERFACE_PORT=${INTERFACE_PORT}

  # racing interface
  interface:
    build: ./interface  
    container_name: racing-interface
    ports:
      - "${INTERFACE_PORT}:3000"
    environment:
      - API_PORT=${API_PORT}
    depends_on:
      - api
