version: '3'

services:
  # racing API
  api:
    build: ./api 
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}

  # racing interface
  willow:
    build: ./interface  
    container_name: racing-interface
    ports:
      - "3000:3000"
    environment:
      - API_HOST=${API_HOST}
    depends_on:
      - api



