version: '3'

services:
  # racing API
  api:
    build: ./api 
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - RIOT_KEY=${RIOT_KEY}

  # racing interface
  willow_tech:
    build: ./interface  
    container_name: interface
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api



